name: Deploy
on: workflow_dispatch
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                path: ~/.npm
                key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
            - name: Install dependencies
              run: npm ci
            - name: Test code
              run: npm test
    build:
      needs: test
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Cache dependencies
          uses: actions/cache@v3
          with:
            path: ~/.npm
            key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
        - name: Install dependencies
          run: npm ci
        - name: Build code
          run: npm run build
        - name: Upload build artifacts
          uses: actions/upload-artifact@v3
          with: 
            name: build-artifacts
            path: dist/
    deploy:
      needs: build
      runs-on: ubuntu-latest
      steps: 
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Download build artifacts
          uses: actions/download-artifact@v3
          with:
            name: build-artifacts
        - name: Deploy to server
          run: echo "Deploying to server..."