name: Deploy
on: workflow_dispatch
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
            - name: Test code
              run: npm test
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
            - name: Lint code
              run: npm run lint
